Antonio Fernandes Valadares - 11711ECP015 \
Computação Evolutiva \
Universidade Federal de Uberlândia - Engenharia de computação \
Professor: Keiji Yamanaka \
Trabalho 5 : Problema do caixeiro viajante

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [76]:
!pip install plotly --upgrade

In [77]:
POINTS = 20

In [78]:
x = np.random.random(size=POINTS * 2) * 10
x = x.reshape(POINTS,2)
x

array([[7.58539157, 4.41417719],
       [4.00778417, 3.1528152 ],
       [3.13977566, 4.90969562],
       [1.90112052, 0.39488963],
       [1.33748011, 6.9824603 ],
       [8.49611003, 0.09549954],
       [9.56118783, 2.17721826],
       [9.98418329, 0.75282617],
       [5.32313872, 0.46352536],
       [6.30043052, 2.68421667],
       [9.1773917 , 8.48464444],
       [5.14158286, 0.7535182 ],
       [9.03086536, 9.22614162],
       [9.35030282, 3.2027074 ],
       [0.91412284, 6.42471738],
       [0.25731882, 5.67602112],
       [9.72883246, 2.30294309],
       [7.1858604 , 5.79794149],
       [5.69635192, 4.54983131],
       [5.36059443, 2.42089344]])

In [79]:
x[:,0]

array([7.58539157, 4.00778417, 3.13977566, 1.90112052, 1.33748011,
       8.49611003, 9.56118783, 9.98418329, 5.32313872, 6.30043052,
       9.1773917 , 5.14158286, 9.03086536, 9.35030282, 0.91412284,
       0.25731882, 9.72883246, 7.1858604 , 5.69635192, 5.36059443])

Problema: Conectar esses pontos de forma com que a distância percorrida seja e menor possível.

In [80]:
grafico = px.scatter(x = x[:,0], y = x[:,1], text=np.arange(0,POINTS,1, dtype=int))
grafico.update_traces(textposition='top center')
grafico.show()

# Funções

In [81]:
import random

In [82]:
## Gerar uma população inicial
# Cada cromossomo será representado pela sequência de pontos a serem percorridos

def initial_population(size):
  #elementos = ''.join(str(e) for e in labels)
  elementos = np.arange(0,POINTS,1, dtype=int)

  caminhos = []
  for i in range(0,size):
    #caminhos.append(''.join(random.sample(elementos,len(elementos))))
    np.random.shuffle(elementos)
    caminhos.append([e for e in elementos])

  return np.array(caminhos)


caminhos = initial_population(size = 20)
caminhos


array([[ 1,  4, 10,  7, 16,  3,  8, 14,  5, 19, 15, 11, 13,  0,  9, 18,
         2,  6, 17, 12],
       [ 8, 13, 14, 18, 12, 19,  2,  1,  7, 17,  6, 16,  9, 10,  4,  3,
         5, 11,  0, 15],
       [ 8,  6, 15,  2, 17, 14,  0,  1, 11,  3,  7, 18, 13, 19,  5, 16,
         9,  4, 12, 10],
       [10,  2,  9,  1,  3, 15,  7,  6,  5,  4,  8, 17, 19, 11, 14, 13,
        18, 12, 16,  0],
       [14, 15, 11,  5, 12,  0,  4,  8,  3,  6, 19, 10,  7, 13, 18,  1,
        16, 17,  2,  9],
       [19,  7,  1,  5,  9, 18,  8,  2, 16, 12,  3, 10, 11,  4, 17, 14,
         0, 15,  6, 13],
       [17,  0, 10, 16, 11,  8, 18,  2,  1,  3,  9,  7, 12, 19,  4, 15,
         6,  5, 13, 14],
       [10,  0,  9,  4, 18, 17, 14, 13,  8, 16, 12,  6, 19,  1,  7, 11,
         5,  3, 15,  2],
       [15, 10, 18,  7,  5, 14, 19, 16,  4, 11,  0, 13,  9,  2,  6,  1,
         3,  8, 12, 17],
       [ 9, 10, 19,  6, 15, 18, 16, 11,  3,  5, 17,  8, 13,  2,  1, 14,
         7,  4,  0, 12],
       [ 8,  4,  7, 11, 13,  9

In [83]:
caminhos[0,:]

array([ 1,  4, 10,  7, 16,  3,  8, 14,  5, 19, 15, 11, 13,  0,  9, 18,  2,
        6, 17, 12])

In [84]:
## Calcular o fitness de cada indíviduo da população
#  Fitness = a distância total a ser percorrida por cada caminho

def calc_dist(pontos):
  dist = 0

  for i in range(1, len(pontos)):
    dist += np.linalg.norm(x[int(pontos[i])] - x[int(pontos[i-1])])

  dist += np.linalg.norm(x[int(pontos[-1])] - x[int(pontos[0])])

  return dist


def fitness(caminhos, size, verbose=False):
  
  fitness = np.zeros((size,))
  for i in range(0,len(caminhos)):
    
    fitness[i] = calc_dist(caminhos[i,:])

  population = np.column_stack((caminhos, fitness))
  population = population[np.argsort(population[:,-1])]
  
  return population


population = fitness(caminhos, size=20)
population

array([[  1.        ,   2.        ,  18.        ,   6.        ,
          0.        ,  11.        ,   8.        ,  19.        ,
         14.        ,  15.        ,   9.        ,  13.        ,
         10.        ,  17.        ,   7.        ,  16.        ,
          5.        ,   3.        ,   4.        ,  12.        ,
         83.18482777],
       [ 17.        ,   0.        ,  10.        ,  16.        ,
         11.        ,   8.        ,  18.        ,   2.        ,
          1.        ,   3.        ,   9.        ,   7.        ,
         12.        ,  19.        ,   4.        ,  15.        ,
          6.        ,   5.        ,  13.        ,  14.        ,
         93.30551034],
       [  8.        ,   6.        ,  15.        ,   2.        ,
         17.        ,  14.        ,   0.        ,   1.        ,
         11.        ,   3.        ,   7.        ,  18.        ,
         13.        ,  19.        ,   5.        ,  16.        ,
          9.        ,   4.        ,  12.        ,  10.    

In [85]:
x_caminho = []
for k in population[0,:POINTS]:
  x_caminho.append(x[int(k),0])
x_caminho.append(x_caminho[0])

#x_caminho

In [86]:
y_caminho = []
for k in population[0,:POINTS]:
  y_caminho.append(x[int(k), 1])
y_caminho.append(y_caminho[0])

#y_caminho

In [87]:
grafico = px.line(x = x_caminho, y = y_caminho)
grafico2 = px.scatter(x = x[:,0], y = x[:,1], text=np.arange(0,POINTS,1, dtype=int))
grafico2.update_traces(textposition='top center')
grafico3 = go.Figure(data=grafico.data + grafico2.data)
grafico3.show()

In [88]:
def torneio(population, k, size):

  p = np.random.choice(np.arange(0,size), size=k)

  c = np.array([population[p[i],:] for i in range(k)])

  c = c[c[:, -1].argsort()]

  return list(c[0,:POINTS])


def crossover(population, size, crossover_rate=0.6, k=3, elit=1):
  new_population = []

  for i in range(elit):
    new_population.append(list(population[i,:POINTS]))


  while(len(new_population) < size):
    p1 = torneio(population, k, size)
    p2 = torneio(population, k, size)


    if(np.random.random() < crossover_rate):
      crossoverpoint = random.randint(0,len(p1))
      crossoverpoint2 = random.randint(0,len(p1))
      f = []

      count = 0
      for i in p1:
        if(count == crossoverpoint):
          break
        if(i not in p2[crossoverpoint:crossoverpoint2]):
          f.append(i)
          count = count + 1
    
      f.extend(p2[crossoverpoint:crossoverpoint2])
            
      f.extend([x for x in p1 if x not in f])

      #f1 = p1[0:crossoverpoint] + p2[crossoverpoint:10]
      #f2 = p2[0:crossoverpoint] + p1[crossoverpoint:10]

      new_population.append(f)

      #new_population.append(f1)
      #new_population.append(f2)

    else:
      new_population.append(p1)
      new_population.append(p2)

    if(len(new_population) > size):
      del new_population[-1]


  return np.array(new_population)


crossover(population, size=10, crossover_rate=1)



array([[ 1.,  2., 18.,  6.,  0., 11.,  8., 19., 14., 15.,  9., 13., 10.,
        17.,  7., 16.,  5.,  3.,  4., 12.],
       [17.,  0., 10., 16., 11.,  8., 18.,  2.,  1.,  3.,  9.,  7., 12.,
        19.,  4., 15.,  6.,  5., 13., 14.],
       [ 1.,  2., 18.,  6.,  0., 11.,  8., 19., 14., 15.,  9., 13., 10.,
        17.,  7., 16.,  5.,  3.,  4., 12.],
       [ 8.,  6., 15.,  2., 17., 14.,  0.,  1., 11.,  3.,  7., 18., 13.,
        19.,  5., 16.,  9.,  4., 12., 10.],
       [17.,  0., 10., 16., 11.,  8., 18.,  2.,  1.,  3.,  9.,  7., 13.,
        12., 19.,  4., 15.,  6.,  5., 14.],
       [ 1.,  4., 10.,  7., 16.,  3.,  8., 14.,  5., 19., 15., 11., 13.,
         0.,  9., 18.,  2.,  6., 17., 12.],
       [ 1.,  2., 18.,  6.,  0., 11.,  8., 19., 14., 15.,  9., 13., 10.,
        17.,  7., 16.,  5.,  3.,  4., 12.],
       [ 1.,  2., 18.,  6.,  0., 11.,  8., 19., 14., 15.,  9., 13., 10.,
        17.,  7., 16.,  5.,  3.,  4., 12.],
       [10.,  2.,  9.,  1.,  3., 15.,  7.,  6.,  5.,  4.,  8., 1

In [89]:
def mut(x):
  mutpoint1 = random.randint(0,POINTS-1)
  mutpoint2 = random.randint(0,POINTS-1)

  #print(x)

  aux = x[mutpoint1]
  x[mutpoint1] = x[mutpoint2]
  x[mutpoint2] = aux

  #print(x)

  return list(x)

def mutation(population, mutation_rate=0.1):
  new_cromossomos = []
  new_cromossomos.append(list(population[0]))

  for element in population[1:]:
    if(np.random.random()<mutation_rate):
      new_cromossomos.append(mut(element))
    else:
      new_cromossomos.append(element)

  cromossomos = []
  for element in new_cromossomos:
    cromossomos.append([int(i) for i in element])

  return np.array(cromossomos)


mutation(population[:,:POINTS], mutation_rate=1)

array([[ 1,  2, 18,  6,  0, 11,  8, 19, 14, 15,  9, 13, 10, 17,  7, 16,
         5,  3,  4, 12],
       [17,  0, 10, 16, 11,  8, 18,  2,  1,  3,  7,  9, 12, 19,  4, 15,
         6,  5, 13, 14],
       [ 8,  6, 15,  1, 17, 14,  0,  2, 11,  3,  7, 18, 13, 19,  5, 16,
         9,  4, 12, 10],
       [11,  0,  9,  4, 18, 17, 14, 13,  8, 16, 12,  6, 19,  1,  7, 10,
         5,  3, 15,  2],
       [14, 15, 11,  5, 12,  3,  4,  8,  0,  6, 19, 10,  7, 13, 18,  1,
        16, 17,  2,  9],
       [ 1,  4, 10,  0, 16,  3,  8, 14,  5, 19, 15, 11, 13,  7,  9, 18,
         2,  6, 17, 12],
       [ 3,  2,  9,  1, 10, 15,  7,  6,  5,  4,  8, 17, 19, 11, 14, 13,
        18, 12, 16,  0],
       [ 7, 16, 15, 13,  8,  3,  1,  2, 10, 14,  6, 19,  0,  5, 11, 18,
        12,  4,  9, 17],
       [ 6,  5, 19,  1, 10, 16, 17, 18,  3,  4,  0, 12, 11,  7,  2,  9,
         8, 13, 15, 14],
       [ 8, 13, 14, 18, 12, 19,  2,  1,  7, 17,  6, 16,  9, 10, 15,  3,
         5, 11,  0,  4],
       [ 5,  3, 11,  1,  4, 12

In [90]:
def genetic_algorithm(size=10, crossover_rate=0.6, k=3, geracoes=10, mutation_rate=0.1, elit=1):

  population = initial_population(size = size)
  

  i = 0
  while(i < geracoes):
    print(i)

    population = fitness(population, size = size)
    population = crossover(population, size = size, elit=elit, crossover_rate=crossover_rate)
    population = mutation(population, mutation_rate=mutation_rate)

    # x_caminho = []
    # for k in population[0,:POINTS]:
    #   x_caminho.append(x[int(k),0])
    # x_caminho.append(x_caminho[0])

    # y_caminho = []
    # for k in population[0,:POINTS]:
    #   y_caminho.append(x[int(k), 1])
    # y_caminho.append(y_caminho[0])

    # grafico = px.line(x = x_caminho, y = y_caminho)
    # grafico2 = px.scatter(x = x[:,0], y = x[:,1], text=np.arange(0,POINTS,1, dtype=int))
    # grafico2.update_traces(textposition='top center')
    # grafico3 = go.Figure(data=grafico.data + grafico2.data)
    # grafico3.show()


    i += 1

  
  return population


#genetic_algorithm()

# Testes


In [96]:
population = genetic_algorithm(size = 100, mutation_rate=0.1, geracoes = 1000, crossover_rate=0.6, elit=1)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [97]:
x_caminho = []
for k in population[0,:POINTS]:
  x_caminho.append(x[int(k),0])
x_caminho.append(x_caminho[0])

#x_caminho

In [98]:
y_caminho = []
for k in population[0,:POINTS]:
  y_caminho.append(x[int(k), 1])
y_caminho.append(y_caminho[0])

#y_caminho

In [99]:
grafico = px.line(x = x_caminho, y = y_caminho)
grafico2 = px.scatter(x = x[:,0], y = x[:,1], text=np.arange(0,POINTS,1, dtype=int))
grafico2.update_traces(textposition='top center')
grafico3 = go.Figure(data=grafico.data + grafico2.data)
grafico3.show()

In [95]:
population[0]

array([ 9, 19, 11,  8,  5,  7,  6, 16, 13,  0, 18,  1,  3, 15, 14,  4,  2,
       12, 10, 17])