Antonio Fernandes Valadares - 11711ECP015 \
Computação Evolutiva \
Universidade Federal de Uberlândia - Engenharia de computação \
Professor: Keiji Yamanaka \
Trabalho 7 : Tratamento de restrições

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Objetivo: Minimizar a função F(X_1, X_2), sujeito as restrições \

X_1 + X_2 - 0.5 <= 0 e X_1 - X_2 - 2 = 0, \
para -3<=X_1<=5 e -3<=X_2<=5


In [23]:
# Portanto a função a ser minimizada é

rp = 1 # coeficiente de penalização

def funcao(X, rp=rp):
  return (X[0] - 1)**2 + (X[1] - 1)**2 + rp*((max(0.0, X[0] + X[1] - 0.5))**2 + (X[0] - X[1] - 2)**2)

funcao([1, 2])

16.25

In [24]:
def initial_population(size):

  population = (8) * np.random.rand(size, 2) - 3
  
  return population

In [25]:
population = initial_population(10)
population

array([[ 4.00816991,  3.47168417],
       [-0.79456085,  0.03664352],
       [-1.2111531 ,  0.26935055],
       [ 3.87745934, -2.28758332],
       [-0.65044895,  4.1867171 ],
       [ 4.08973636, -1.58762176],
       [-1.28006267,  2.45295445],
       [ 1.288674  ,  3.36754186],
       [-1.8675899 ,  0.64749515],
       [ 1.10365698,  3.95995005]])

Calcula o fitness dos individuos

In [26]:
funcao(population[3])

37.6233863673089

In [27]:
def fitness(population, size, rp):
  fitness = np.zeros((size,))

  for i in range(0, len(population)):
    fitness[i] = funcao(population[i], rp=rp)

  population = np.column_stack((population, fitness))
  population = population[np.argsort(population[:,-1])]

  return population

In [28]:
population = fitness(population, 10, rp)
population

array([[-7.94560851e-01,  3.66435232e-02,  1.21642226e+01],
       [-1.21115310e+00,  2.69350548e-01,  1.75369523e+01],
       [-1.86758990e+00,  6.47495149e-01,  2.87333245e+01],
       [ 4.08973636e+00, -1.58762176e+00,  3.37736828e+01],
       [ 3.87745934e+00, -2.28758332e+00,  3.76233864e+01],
       [ 1.28867400e+00,  3.36754186e+00,  3.95998805e+01],
       [-1.28006267e+00,  2.45295445e+00,  4.06300310e+01],
       [ 1.10365698e+00,  3.95995005e+00,  5.31821405e+01],
       [ 4.00816991e+00,  3.47168417e+00,  6.60185460e+01],
       [-6.50448953e-01,  4.18671710e+00,  6.88449114e+01]])

In [29]:
def crossover(population, size, crossover_rate, k):
  new_population = []

  new_population.append(list(population[0,:2]))
  while(len(new_population) < size):
    
    #torneio
    p1 = population[np.min(np.random.choice(np.arange(0,size), size=k)),:2]

    p2 = population[np.min(np.random.choice(np.arange(0,size), size=k)),:2]

    if np.random.random() <= crossover_rate:
      beta = np.random.random()
      f1 = beta * p1 + (1-beta) * p2
      f2 = (1-beta) * p1 + beta * p2
      new_population.append(list(f1))
      new_population.append(list(f2))
    else:
      new_population.append(list(p1))
      new_population.append(list(p2))

  if len(new_population) > size:
    del new_population[-1]


  return np.array(new_population)

In [30]:
crossover(population, 10, 0, 3)

array([[-0.79456085,  0.03664352],
       [ 4.08973636, -1.58762176],
       [-0.79456085,  0.03664352],
       [-0.79456085,  0.03664352],
       [-0.79456085,  0.03664352],
       [-1.8675899 ,  0.64749515],
       [-0.79456085,  0.03664352],
       [-1.2111531 ,  0.26935055],
       [ 3.87745934, -2.28758332],
       [-0.79456085,  0.03664352]])

In [31]:
def mutation(population, mutation_rate):

  for element in population:
    if np.random.random() <= mutation_rate:
      element[np.random.randint(2)] = (8) * np.random.rand() - 3

  return population

In [32]:
mutation(population, 1)

array([[ 1.15136334e-01,  3.66435232e-02,  1.21642226e+01],
       [-1.92428472e+00,  2.69350548e-01,  1.75369523e+01],
       [-1.86758990e+00, -1.71808404e-01,  2.87333245e+01],
       [-1.41459965e+00, -1.58762176e+00,  3.37736828e+01],
       [ 3.87745934e+00,  4.27952277e+00,  3.76233864e+01],
       [ 1.71649146e+00,  3.36754186e+00,  3.95998805e+01],
       [-2.68304591e+00,  2.45295445e+00,  4.06300310e+01],
       [ 3.76793752e+00,  3.95995005e+00,  5.31821405e+01],
       [ 4.00816991e+00,  3.54666184e+00,  6.60185460e+01],
       [ 5.60262005e-01,  4.18671710e+00,  6.88449114e+01]])

In [36]:
def genetic_algorithm(size=20, crossover_rate=0.6, k=3, geracoes=100, mutation_rate=0.1, rp=0.1):
  population = initial_population(size)

  for _ in range(geracoes):
    population = fitness(population, size, rp)
    population = crossover(population, size, crossover_rate, k)
    population = mutation(population, mutation_rate)

  population = fitness(population,size, rp)

  return population

In [48]:
genetic_algorithm(size=50, geracoes=1000, rp=1)

array([[ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.08334813],
       [ 1.16666667, -0.16444598,  2.083